// src/components/footer/index.tsx
import React from "react";
import "./index.less";

export default function Footer() {
  return (
    <footer>
      <div className="inner">
        <a className="source" href="https://github.com/deno-china/website">
          源码地址
        </a>
        <div className="desc">
          DENOCN 社区为国内最专业的 Deno 开源技术社区，致力于 Deno
          技术学习与研究。
        </div>
        <div className="sponsor">目前还没有赞助商，服务器建在香港阿里云。</div>
      </div>
    </footer>
  );
}

// src/components/footer.svelte
<style lang="less" global>
  footer {
    position: absolute;
    bottom: 0;
    background: #424242;
    width: 100%;
    .inner {
      max-width: 1400px;
      width: 90%;
      margin: auto;
      padding: 15px 0;
      .source {
        font-size: 14px;
        text-decoration: none;
        color: #eee;
      }
      .desc {
        font-size: 13px;
        color: #bbb;
      }
      .sponsor {
        font-size: 13px;
        color: #bbb;
      }
    }
  }
</style>

<footer>
  <div class="inner">
    <a className="source" href="https://github.com/deno-china/website">
      源码地址
    </a>
    <div class="desc">
      DENOCN 社区为国内最专业的 Deno 开源技术社区，致力于 Deno 技术学习与研究。
    </div>
    <div class="sponsor">目前还没有赞助商，服务器建在香港阿里云。</div>
  </div>
</footer>
